name: build
on:
  - push
  - pull_request
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os:   [ubuntu-latest, macos-latest, windows-latest]
        ruby: [ '2.7', '3.0' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache libui shared library
        id: cache-libui
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-libui-${{ hashFiles('libui.so') }}
          restore-keys: |
            ${{ runner.os }}-libui
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake vendor:all
          bundle exec rake test
